"""empty message

Revision ID: 09acbb7f23a2
Revises: 3d6b36b7396b
Create Date: 2020-06-10 21:49:00.012717

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "09acbb7f23a2"
down_revision = "3d6b36b7396b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "media",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=300), nullable=True),
        sa.Column("type", sa.String(length=120), nullable=True),
        sa.Column("data", sa.LargeBinary(), nullable=True),
        sa.Column("index", sa.Integer(), nullable=True),
        sa.Column("test_history_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["test_history_id"], ["test_history.id"],),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("media")
    # ### end Alembic commands ###
