"""empty message

Revision ID: 0aaeda212380
Revises: feef539bd698
Create Date: 2020-07-10 16:27:38.205883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "0aaeda212380"
down_revision = "feef539bd698"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "media",
        sa.Column(
            "created_datetime",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("media", "created_datetime")
    # ### end Alembic commands ###
