"""empty message

Revision ID: 5490b79c969f
Revises: 0aaeda212380
Create Date: 2020-08-18 11:53:58.558971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5490b79c969f'
down_revision = '0aaeda212380'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test', sa.Column('test_resolution_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'test', 'test_resolution', ['test_resolution_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'test', type_='foreignkey')
    op.drop_column('test', 'test_resolution_id')
    # ### end Alembic commands ###
