"""empty message

Revision ID: 7fbc4dda2333
Revises:
Create Date: 2020-09-21 19:39:51.030379

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "7fbc4dda2333"
down_revision = "5490b79c969f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("test", sa.Column("is_flaky", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("test", "is_flaky")
    # ### end Alembic commands ###
