"""empty message

Revision ID: 9fe0f0373ea2
Revises: 139b3146bf01
Create Date: 2020-11-23 23:32:29.911178

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9fe0f0373ea2"
down_revision = "139b3146bf01"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "smart_links",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("environment", sa.String(length=2000), nullable=True),
        sa.Column("smart_link", sa.String(length=2000), nullable=True),
        sa.Column("label", sa.String(length=30), nullable=True),
        sa.Column("color", sa.String(length=20), nullable=True),
        sa.ForeignKeyConstraint(["project_id"], ["project.id"],),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("test", sa.Column("data", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("test", "data")
    op.drop_table("smart_links")
    # ### end Alembic commands ###
