"""empty message

Revision ID: feef539bd698
Revises: 3d6b36b7396b
Create Date: 2020-06-17 16:54:58.206677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "feef539bd698"
down_revision = "3d6b36b7396b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "media",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=300), nullable=True),
        sa.Column("type", sa.String(length=120), nullable=True),
        sa.Column("data", sa.LargeBinary(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("test_history", sa.Column("media", sa.JSON(), nullable=True))
    op.add_column("test_retries", sa.Column("media", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("test_retries", "media")
    op.drop_column("test_history", "media")
    op.drop_table("media")
    # ### end Alembic commands ###
